### ISSUE TITLE
Add base rtl support

### ISSUE THREAD

**Issue by hellcp** [openSUSE/chameleon#40]
This does look a touch broken, but it's a big improvement for those that need it:
```css
html[lang^=ar] body,
html[lang^=he] body,
html[lang^=sy] body,
html[lang^=sam] body,
html[lang^=men] body,
html[lang^=man] body,
html[lang^=wo] body,
html[lang^=ff] body {
 direction:rtl;
 text-align: right;
}
```
